"""Analytics tool — wires proactive issue detection into the chat agent.

The Operations dashboard and Analytics page already compute real, data-backed
insights (`AnalyticsService`). Without this tool, a chat question like "analyze
the support activity" or "which tickets are approaching SLA breach" had no way
to reach that data and fell back to generic document retrieval — a genuine gap
between what the product *has* and what the agent can *say*. This tool closes
it: every fact it returns is counted from the database, never generated by the
LLM, and it is only available to authorised internal roles (support/manager/
admin), matching who the dashboard itself is for.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from app.schemas.results import Citation
from app.services.analytics_service import AnalyticsService
from app.tools.base import Tool, ToolContext, ToolResult

_STRUCTURED_CITATION = Citation(
    document_code="STRUCTURED-DATA",
    title="ParcelPilot operational database",
    heading="Live ticket/order/escalation aggregates",
    source_type="structured_data",
    status="current",
    authority_rank=5,
)


class AnalyticsArgs(BaseModel):
    focus: Literal["insights", "clusters", "sla_risk", "cross_customer", "summary"] = Field(
        default="insights",
        description="Which angle to summarise: proactive insights, recurring issue clusters, SLA-breach risk, cross-customer patterns, or a plain severity/volume summary.",
    )


class AnalyticsTool(Tool):
    name = "analytics_tool"
    description = (
        "Proactive issue detection and analytics: urgent/high-severity tickets, SLA breaches "
        "and near-breaches, recurring known-issue clusters with counts, carrier-fault patterns, "
        "and cross-customer impact — all computed live from the database. Internal roles only."
    )
    input_model = AnalyticsArgs
    required_permission = "view_ops"

    def run(self, ctx: ToolContext, args: AnalyticsArgs) -> ToolResult:
        svc = AnalyticsService(ctx.session, ctx.principal)
        dash = svc.dashboard()
        an = svc.analytics()

        lines: list[str] = []
        if args.focus == "clusters":
            if dash["recurring_problems"]:
                for k in dash["recurring_problems"]:
                    lines.append(f"{k['code']} ({k['title']}): {k['count']} ticket(s) — {k['guidance']}")
            else:
                lines.append("No recurring known-issue clusters detected in the tickets currently in scope.")
        elif args.focus == "sla_risk":
            breaches = dash["sla_breaches"]
            if breaches:
                for b in breaches:
                    lines.append(f"{b['code']} ({b['account']}, {b['severity']}): target {b['sla_target']} — BREACHED.")
            else:
                lines.append("No open tickets are currently breaching their SLA.")
            near = [t for t in dash["high_severity_tickets"] if not t["breached"]]
            for t in near:
                lines.append(f"{t['code']} ({t['account']}, {t['severity']}): target {t['sla_target']} — within target, watch closely.")
        elif args.focus == "cross_customer":
            for k in dash["recurring_problems"]:
                lines.append(f"{k['code']} ({k['title']}) is affecting {k['count']} ticket(s) across accounts in scope.")
            for c in dash["carrier_problems"]:
                if c["fault_orders"]:
                    lines.append(f"Carrier '{c['carrier']}' is at fault on {c['fault_orders']} of {c['orders']} order(s) in scope — a potential systemic issue, not isolated to one customer.")
            if not lines:
                lines.append("No single issue is currently affecting multiple customers in scope.")
        elif args.focus == "summary":
            sev = {s["severity"]: s["count"] for s in an["severity_distribution"]}
            lines.append(f"Severity: P1={sev.get('P1', 0)}, P2={sev.get('P2', 0)}, P3={sev.get('P3', 0)}.")
            comp = {s["label"]: s["count"] for s in an["sla_compliance"]}
            lines.append(f"SLA compliance (open tickets): {comp.get('Compliant', 0)} compliant, {comp.get('Breached', 0)} breached.")
            if an["top_issues"]:
                lines.append("Top issues: " + ", ".join(f"{i['code']} ({i['count']})" for i in an["top_issues"]) + ".")
            if an["top_customers"]:
                lines.append("Highest open-issue accounts: " + ", ".join(f"{c['name']} ({c['tickets']})" for c in an["top_customers"][:3]) + ".")
        else:  # insights
            lines.extend(dash["ai_insights"])

        summary = " ".join(lines) if lines else "No data-backed insights are available for this scope right now."
        return ToolResult(
            tool=self.name,
            ok=True,
            summary=summary,
            data={"focus": args.focus, "dashboard": dash, "analytics": an, "lines": lines},
            citations=[_STRUCTURED_CITATION],
        )
